#!/usr/bin/env bash
OS=$(uname -s)

VIDEO_DEVICE_ID=$(~/.config/hypr/custom/scripts/videoid)
GLSL_FILES=($(find ~/.config/hypr/shaders/ -name "*.glsl"))
REFRESH_TIME=300

if pgrep -f "glpaper $VIDEO_DEVICE_ID" > /dev/null
then
    pkill -f "glpaper $VIDEO_DEVICE_ID"
    notify-send --icon=dialog-warning "$USER" "GLSL KILLED ${TIMECODE} " > /dev/null 2>&1
fi

NEXT_REFRESH=$(( $(date +%s) + $REFRESH_TIME ))
TIMECODE=$(( $(date +%s) / $REFRESH_TIME ))
notify_file=$(basename "${GLSL_FILES[${RANDOM:0:1}%${#GLSL_FILES[@]}]}" .glsl)
notify_file="${notify_file##*/}"
notify-send --icon=dialog-warning "$USER" "LETS GLSL $(date -u -d @${TIMECODE} '+%H:%M:%S') ${notify_file}" > /dev/null 2>&1

while [ $(date +%s) -lt $NEXT_REFRESH ]
do
    glpaper $VIDEO_DEVICE_ID "${GLSL_FILES[${RANDOM:0:1}%${#GLSL_FILES[@]}]}" &
    sleep $REFRESH_TIME
done


else
    notify-send --icon=dialog-warning "$USER" "Erreur : la valeur stockée dans ~/.config/hypr/custom/scripts/videoid n'est pas un entier" > /dev/null 2>&1
 
    if [[ $VIDEO_DEVICE_ID =~ ^[0-9]+$ ]]
    then
        echo $VIDEO_DEVICE_ID > ~/.config/hypr/custom/scripts/videoid
        glpaper $VIDEO_DEVICE_ID ~/.config/hypr/shaders/hg.glsl
    else
        notify-send --icon=dialog-warning "$USER" "Impossible de récupérer l'ID du VIDEO DEVICE" > /dev/null 2>&1
    fi
fi




