#!/usr/bin/env bash

# Configuration de wofi
SCRIPTS="$HOME/.config/hypr/custom/scripts"
CONFIG_FILE="$SCRIPTS/glpaper.config"
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Erreur : Le fichier de configuration wofi n'existe pas : $CONFIG_FILE"
    exit 1
fi

# Définis le répertoire et l'application
SCRIPTS="$HOME/.config/hypr/custom/scripts/"
DIRECTORY="$HOME/.config/hypr/shaders/glsl"
APPLICATION="glpaper" # Remplace par l'application de ton choix
VIDEOID=$(xrandr | grep 'HDMI-A-1' | cut -d' ' -f1 | cut -d'+' -f1)

# Récupère les fichiers du répertoire
FILES=()
while IFS= read -r -d $'\0'; do
    FILENAME=$(basename "$REPLY")
    FILES+=("$FILENAME")
done < <(find "$DIRECTORY" -maxdepth 1 -type f -name "*.glsl" -print0)

# Crée le menu avec wofi
RESULT=$(printf '%s\n' "${FILES[@]}" | wofi -G -w 4 -c "$CONFIG_FILE" --show dmenu --matching fuzzy --config )

# Quitte si aucun élément n'a été sélectionné
if [ -z "$RESULT" ]; then
    exit 1
fi

# Votre commande ou chemin vers le script qui génère la sortie pour wofi.
FULLPATH="$DIRECTORY/$RESULT"

# Vérifie si le fichier existe.
if [ ! -f "$FULLPATH" ]; then
    snd-notify "Erreur : Le fichier '$FULLPATH' n'existe pas"
    exit 1
fi

# Exécute l'application avec des arguments, s'il y a une erreur, notification de l'utilisateur.
if ! "$APPLICATION" "$VIDEOID" "$FULLPATH"; then
    snd-notify "Erreur d'exécution : Le programme $APPLICATION a retourné une erreur"
fi
