#!/bin/bash

# Créez l'utilisateur 'glpaper' sans un répertoire home
sudo useradd -M glpaper || true  # Évite l'interruption du script si l'utilisateur existe déjà

# Ajoutez l'utilisateur '$USER' au groupe 'video'
sudo usermod -aG video $USER
bg_daemon_script="bgDaemon"
# Créez le répertoire glpaper pour les exécutables
local_bin="$HOME/.local/bin"
local_run="$HOME/.local/run"

mkdir -p "$local_bin/glpaper"
mkdir -p "$local_run/glpaper"
cp "$bg_daemon_script" "$local_bin/glpaper/."

# Changez la propriété et les permissions des répertoires
chown -R $USER:video "$local_bin/glpaper"
chown -R $USER:video "$local_run/glpaper"
chmod -R 750 "$local_bin/glpaper"
chmod -R 750 "$local_run/glpaper"

# Installez le daemon et service dans systemd
sudo cp bgDaemon.service /etc/systemd/system/
echo $$ > "$local_run/glpaper/bgDaemon.pid"

# Activez les daemons
sudo systemctl daemon-reload
sudo systemctl enable bgDaemon.service
sudo systemctl start bgDaemon.service
